# Generated by Django 4.2.30 on 2026-06-21 16:54

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(default='低碳新人', max_length=30, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, default='', max_length=255, verbose_name='头像URL')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '保密')], default='unknown', max_length=10, verbose_name='性别')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('student_id', models.CharField(blank=True, default='', max_length=20, verbose_name='学号')),
                ('college', models.CharField(blank=True, default='', max_length=50, verbose_name='学院')),
                ('major', models.CharField(blank=True, default='', max_length=50, verbose_name='专业')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='累计绿色积分')),
                ('available_points', models.PositiveIntegerField(default=0, verbose_name='可用积分')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='等级')),
                ('streak_days', models.PositiveIntegerField(default=0, verbose_name='连续打卡天数')),
                ('last_checkin_date', models.DateField(blank=True, null=True, verbose_name='最后打卡日期')),
                ('total_carbon_reduction', models.FloatField(default=0.0, verbose_name='累计减碳量(kg)')),
                ('total_tasks_done', models.PositiveIntegerField(default=0, verbose_name='累计完成任务数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-total_points'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
