# Generated by Django 4.2.30 on 2026-06-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='徽章名称')),
                ('icon', models.CharField(default='🏅', max_length=10, verbose_name='图标(emoji)')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='描述')),
                ('condition_points', models.PositiveIntegerField(default=0, verbose_name='达成所需累计积分')),
                ('condition_tasks', models.PositiveIntegerField(default=0, verbose_name='达成所需完成任务数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '徽章',
                'verbose_name_plural': '徽章',
                'ordering': ['condition_points'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='挑战名称')),
                ('description', models.TextField(blank=True, default='', max_length=500, verbose_name='挑战描述')),
                ('cover', models.CharField(default='🌍', max_length=255, verbose_name='封面图URL/emoji')),
                ('tag', models.CharField(blank=True, default='热门', max_length=20, verbose_name='标签')),
                ('points', models.PositiveIntegerField(default=100, verbose_name='完成积分')),
                ('target_count', models.PositiveIntegerField(default=7, verbose_name='目标完成次数')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.CharField(choices=[('ongoing', '进行中'), ('ended', '已结束'), ('upcoming', '即将开始')], default='ongoing', max_length=20, verbose_name='状态')),
                ('participants_count', models.PositiveIntegerField(default=0, verbose_name='参与人数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '校园挑战',
                'verbose_name_plural': '校园挑战',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='当前进度')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            options={
                'verbose_name': '挑战参与',
                'verbose_name_plural': '挑战参与',
            },
        ),
        migrations.CreateModel(
            name='CharityProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='项目名称')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='项目描述')),
                ('icon', models.CharField(default='🌳', max_length=10, verbose_name='图标(emoji)')),
                ('cost', models.PositiveIntegerField(default=50, verbose_name='捐赠所需积分')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('total_donated', models.PositiveIntegerField(default=0, verbose_name='累计捐赠次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公益项目',
                'verbose_name_plural': '公益项目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=80, verbose_name='项目名称快照')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='消耗积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='捐赠时间')),
            ],
            options={
                'verbose_name': '捐赠记录',
                'verbose_name_plural': '捐赠记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='小组名称')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='小组描述')),
                ('icon', models.CharField(default='👥', max_length=10, verbose_name='图标(emoji)')),
                ('member_count', models.PositiveIntegerField(default=0, verbose_name='成员数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '低碳小组',
                'verbose_name_plural': '低碳小组',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GroupCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(auto_now_add=True, verbose_name='签到日期')),
                ('points_earned', models.PositiveIntegerField(default=3, verbose_name='获得积分')),
            ],
            options={
                'verbose_name': '小组签到',
                'verbose_name_plural': '小组签到',
                'ordering': ['-checkin_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('content', models.CharField(blank=True, default='', max_length=200, verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=80, verbose_name='商品名称快照')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='消耗积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
            ],
            options={
                'verbose_name': '兑换记录',
                'verbose_name_plural': '兑换记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='商品名称')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='商品描述')),
                ('image', models.CharField(default='🎁', max_length=255, verbose_name='商品图片URL/emoji')),
                ('cost', models.PositiveIntegerField(default=100, verbose_name='兑换积分')),
                ('stock', models.IntegerField(default=100, verbose_name='库存')),
                ('tag', models.CharField(choices=[('', '普通'), ('hot', '热门'), ('new', '新品'), ('rare', '稀有')], default='', max_length=10, verbose_name='标签')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商城商品',
                'verbose_name_plural': '商城商品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='任务描述')),
                ('category', models.CharField(choices=[('dining', '餐饮'), ('energy', '用电'), ('travel', '出行'), ('shopping', '购物'), ('study', '学习'), ('resource', '资源')], default='dining', max_length=20, verbose_name='行为类别')),
                ('icon', models.CharField(default='🌱', max_length=10, verbose_name='图标(emoji)')),
                ('points', models.PositiveIntegerField(default=5, verbose_name='积分奖励')),
                ('carbon_reduction', models.FloatField(default=0.5, verbose_name='减碳量(kg)')),
                ('daily_limit', models.PositiveIntegerField(default=1, verbose_name='每日次数上限')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '低碳任务',
                'verbose_name_plural': '低碳任务',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(auto_now_add=True, verbose_name='完成日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='完成时间')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='获得积分')),
            ],
            options={
                'verbose_name': '任务记录',
                'verbose_name_plural': '任务记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='获得时间')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='core.badge')),
            ],
            options={
                'verbose_name': '用户徽章',
                'verbose_name_plural': '用户徽章',
            },
        ),
    ]
