# Generated by Django 4.2.30 on 2026-07-24 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonopolyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('chance', '绿色机遇'), ('crisis', '碳危机')], max_length=10, verbose_name='事件类型')),
                ('description', models.CharField(max_length=200, verbose_name='事件描述')),
                ('points_change', models.IntegerField(default=0, verbose_name='积分变动')),
                ('extra_dice', models.PositiveIntegerField(default=0, verbose_name='额外骰子')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '大富翁事件',
                'verbose_name_plural': '大富翁事件',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MonopolyTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(unique=True, verbose_name='位置(1-24)')),
                ('tile_type', models.CharField(choices=[('start', '起点'), ('scene', '低碳场景'), ('chance', '绿色机遇'), ('crisis', '碳危机'), ('task', '任务格'), ('charity', '公益格'), ('trap', '高碳陷阱')], max_length=20, verbose_name='格子类型')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('icon', models.CharField(default='📍', max_length=10, verbose_name='图标')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='描述')),
                ('claim_cost', models.PositiveIntegerField(default=0, verbose_name='认领积分')),
                ('upgrade_cost', models.PositiveIntegerField(default=0, verbose_name='升级积分')),
                ('base_toll', models.PositiveIntegerField(default=0, verbose_name='基础过路费')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '大富翁格子',
                'verbose_name_plural': '大富翁格子',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['category', 'condition_points'], 'verbose_name': '徽章', 'verbose_name_plural': '徽章'},
        ),
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('general', '通用'), ('monopoly', '大富翁')], default='general', max_length=20, verbose_name='徽章类别'),
        ),
        migrations.AddField(
            model_name='badge',
            name='monopoly_key',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='大富翁触发标识'),
        ),
        migrations.CreateModel(
            name='MonopolyProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='等级')),
                ('total_toll_collected', models.PositiveIntegerField(default=0, verbose_name='累计收取过路费')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='认领时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monopoly_properties', to=settings.AUTH_USER_MODEL)),
                ('tile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='core.monopolytile')),
            ],
            options={
                'verbose_name': '大富翁场景',
                'verbose_name_plural': '大富翁场景',
            },
        ),
        migrations.CreateModel(
            name='MonopolyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='当前位置')),
                ('dice_count', models.PositiveIntegerField(default=0, verbose_name='可用骰子次数')),
                ('total_steps', models.PositiveIntegerField(default=0, verbose_name='累计步数')),
                ('laps', models.PositiveIntegerField(default=0, verbose_name='绕场圈数')),
                ('is_trapped', models.BooleanField(default=False, verbose_name='是否被困')),
                ('trap_attempts', models.PositiveIntegerField(default=0, verbose_name='脱困答题次数')),
                ('last_play_at', models.DateTimeField(blank=True, null=True, verbose_name='最后游戏时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monopoly', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '大富翁玩家',
                'verbose_name_plural': '大富翁玩家',
            },
        ),
        migrations.CreateModel(
            name='MonopolyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('roll', '掷骰'), ('claim', '认领'), ('upgrade', '升级'), ('toll', '过路费'), ('event', '事件'), ('task', '任务'), ('charity', '公益'), ('trap', '陷阱')], max_length=20, verbose_name='动作类型')),
                ('tile_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='相关格子')),
                ('dice_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='骰子点数')),
                ('points_change', models.IntegerField(default=0, verbose_name='积分变动')),
                ('description', models.CharField(default='', max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monopoly_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '大富翁日志',
                'verbose_name_plural': '大富翁日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
